//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int ID { get; set; }
        public string ProductArticleNumber { get; set; }
        public int IDProductName { get; set; }
        public int IDEdIzmerenia { get; set; }
        public decimal ProductPrice { get; set; }
        public int ProductMaxDiscount { get; set; }
        public int IDProductManufacturer { get; set; }
        public int IDProductSupplier { get; set; }
        public int IDProductCategory { get; set; }
        public int ProductDiscountAmount { get; set; }
        public int ProductCount { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public byte[] ProductPhotoCode { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual EdIzmerenia EdIzmerenia { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual ProductName ProductName { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
